CREATE DATABASE ASSIGNMENT_1
USE ASSIGNMENT_1
SET SQL_SAFE_UPDATES = 0;
CREATE TABLE WORKER_1(
ID INT,
FIRST_NAME VARCHAR(25),
DEPARTMENT VARCHAR(25),
LOCATION VARCHAR(25),
SALARY INT
);
SELECT * FROM WORKER_1
INSERT INTO WORKER_1 VALUES(1,'AMITABH','DATA','LDH',45000);
INSERT INTO WORKER_1 VALUES(2,'MORISH','SALES','POP',45000);
INSERT INTO WORKER_1 VALUES(3,'RISHAV','DATA','KUC',47000);
INSERT INTO WORKER_1 VALUES(4,'VIPUL','SALES','DLI',48000);
INSERT INTO WORKER_1 VALUES(5,'SATISH','SALES','NDLS',49000);
INSERT INTO WORKER_1 VALUES(6,'ABHI','CONST','JUC',50000);
INSERT INTO WORKER_1 VALUES(7,'VIKAS','CONST','LUCK',51000);
SELECT * FROM WORKER_1


#Q-1. Write an SQL query to fetch “FIRST_NAME” from Worker table using the alias
name as <WORKER_NAME>

SELECT FIRST_NAME FROM WORKER_1


#Q-2. Write an SQL query to fetch unique values of DEPARTMENT from Worker table.

SELECT * FROM WORKER_1

SELECT DISTINCT DEPARTMENT FROM WORKER_1


#Q-3. Write an SQL query to show the last 5 record from a table.

SELECT * FROM WORKER_1

(SELECT * FROM WORKER_1 ORDER BY ID DESC LIMIT 5)
ORDER BY ID ASC;

